version: '3.7'
services:
  app:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - compose.env
    volumes:
      - .:/atu-corsego
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: atu
      POSTGRES_PASSWORD: dbpassword